name: competspa
description: "Sistema de Pagamento por Serviços Ambientais"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ícones da Apple
  cupertino_icons: ^1.0.8

  # localização e mapas
  geolocator: ^14.0.0
  google_maps_flutter: ^2.2.0

  # gráficos
  fl_chart: ^0.71.0
  image_picker: ^0.8.7+3   # captura de imagem

  # novos pacotes
  csv: ^5.0.0
  pdf: ^3.8.1
  printing: ^5.12.0
  share_plus: ^4.0.10

  # armazenamento local e offline queue
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # permissões (Android/iOS)
  permission_handler: ^12.0.0+1

  # estado global
  provider: ^6.0.5

  # HTTP / API
  http: ^1.3.0

  # deep links e url launcher
  url_launcher: ^6.1.7

  # internacionalização / formatação de data
  intl: ^0.20.2

  # Firebase e notificações
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

  # ícones adicionais (WhatsApp)
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_local_notifications:
  platforms:
    android: true
    ios: true
    linux: false  # Desabilite suporte para Linux, caso não esteja usando

