name: competspa
description: "Sistema de Pagamento por Serviços Ambientais"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter e ícones
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter  # inclui intl 0.19.0 para suporte a internacionalização

  # Localização e Mapas
  geolocator: ^14.0.0  # Para obter a localização geográfica
  google_maps_flutter: ^2.3.0  # Para integrar o Google Maps no app

  # Gráficos e Imagens
  fl_chart: ^0.71.0  # Para gráficos interativos
  image_picker: ^1.1.2  # Para selecionar ou tirar fotos

  # CSV, PDF e Compartilhamento
  csv: ^6.0.0  # Para manipulação de arquivos CSV
  pdf: ^3.10.4  # Para gerar documentos PDF
  printing: ^5.12.0  # Para imprimir documentos
  share_plus: ^11.0.0  # Para compartilhar arquivos e conteúdo
  webview_flutter: ^4.2.2  # Para exibir conteúdo web dentro do aplicativo
  exif: ^3.3.0  # Para manipulação de metadados EXIF em imagens
  native_exif:
    git:
      url: https://github.com/cloudacy/native_exif.git

  # Armazenamento Local
  shared_preferences: ^2.2.0  # Para armazenamento de configurações e dados simples
  hive: ^2.2.3  # Banco de dados NoSQL local
  hive_flutter: ^1.1.0  # Integração do Hive com Flutter
  path_provider: ^2.0.10  # Para localização de diretórios no dispositivo

  # Permissões
  permission_handler: ^12.0.0  # Para gerenciar permissões de acesso do usuário

  # Estado e Comunicação com API
  provider: ^6.0.5  # Para gerenciamento de estado
  http: ^1.3.0  # Para fazer requisições HTTP
  url_launcher: ^6.1.7  # Para abrir links externos no navegador
  win32: ^5.12.0  # Para compatibilidade com Windows (caso necessário)

  # Internacionalização / Formatação de Data
  intl: ^0.19.0  # Para suporte a internacionalização e formatação de datas
  flutter_map: ^7.0.2  # Para integração de mapas no app

  flutter_map_marker_popup: ^7.0.0  # Para popups em marcadores do mapa
  flutter_map_geojson: ^1.0.8  # Para integrar dados GeoJSON no mapa
  latlong2: any  # Para trabalhar com coordenadas de latitude e longitude

  # Firebase e Notificações Locais
  firebase_core: ^3.13.0  # Para integração do Firebase com o app
  firebase_messaging: ^15.2.5  # Para gerenciar notificações push com Firebase
  flutter_local_notifications: ^19.1.0  # Para notificações locais no app

  # Ícones Adicionais e Utilitários
  material_design_icons_flutter: ^7.0.7296  # Para ícones adicionais de Material Design
  flutter_launcher_icons: ^0.14.3  # Para personalizar o ícone do aplicativo
  uuid: any  # Para geração de identificadores únicos

  # Easy Localization e Loader
  easy_localization: ^3.0.1  # Para facilitar a tradução e internacionalização do app
  easy_localization_loader: ^2.0.2  # Para carregar arquivos de tradução em tempo de execução

  # Outros
  image: any  # Para manipulação de imagens
  http_parser: any  # Para análise de cabeçalhos HTTP

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # Para aplicar as boas práticas de linting

  # Geração de código para as chaves de tradução
  build_runner: ^2.4.0  # Para gerar código de tradução
  easy_localization_generator: ^0.3.3  # Para gerar as traduções de forma automática

flutter:
  uses-material-design: true

  # Assets de JSON de tradução
  assets:
    - assets/translations/

flutter_local_notifications:
  platforms:
    android: true
    ios: true
    linux: false

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: false
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
